id = "gotest"
name = "Go Test Runnable"
description = "Test Runnable support for Go"
version = "0.1.0"
schema_version = 1
authors = ["Anıl Şenay <anilsenay3@gmail.com>"]
repository = "https://github.com/anilsenay/zed-gotest"
